### PR TITLE
This update includes changes to the Assignment model, the addition of…

### PR DESCRIPTION
**Pull request by whoissegun**
… the Grade model, and the creation of test cases for the Assignment model.

Updated Assignment Model, Created Grade model and also created assignment model test case

### CODE REVIEW

**Comment by whoissegun** [comment]
> 

I wasn't assigned that task. Only assigned to work on the model and create tests

**Comment by abrokinla** [comment]
> I wasn't assigned that task. Only assigned to work on the model and create tests

Please check the link for the details of the task assigned. Do well to check the date as well.

**Review by abrokinla — APPROVED** [review]
Everything looks good here. 
Though I didn’t see the update for documentation.

**Comment by whoissegun** [comment]
> Everything looks good here. Though I didn’t see the update for documentation.

My bad. I'll remember to add it from now

**Pull request merged**
